In [7]:
from padelpy import from_smiles
import pandas as pd
import numpy as np

In [8]:
smiles = pd.read_csv("E://Drug Efficacy project//Data//SMIES.csv")

In [3]:
smiles_list = smiles['SMILES'].tolist()

In [4]:
# smiles_list has smiles of 223 drugs, when tried to extract the features of all 223 at atime, encountered timeout error. henece devided into small chunks of 30 and extracted the features
# by default the timeout value is 12 sec, we had to increase it to 100

In [5]:
smiles_chunks = [smiles_list[x:x+30] for x in range(0, len(smiles_list), 30)]

In [ ]:
# the below code is to derive the features of the drugs and save them to csv files, 
#iam not running them now due to time issues
# i already have the file with derived features (combined of all the 8 files)

In [ ]:
_ = from_smiles(smiles_chunks[0], fingerprints=True, timeout=100, output_csv='drug_descriptors0.csv')

In [ ]:
_ = from_smiles(smiles_chunks[1], fingerprints=True, timeout=100, output_csv='drug_descriptors1.csv')

In [ ]:
_ = from_smiles(smiles_chunks[2], fingerprints=True, timeout=100, output_csv='drug_descriptors2.csv')

In [ ]:
_ = from_smiles(smiles_chunks[3], fingerprints=True, timeout=100, output_csv='drug_descriptors3.csv')

In [ ]:
_ = from_smiles(smiles_chunks[4], fingerprints=True, timeout=200, output_csv='drug_descriptors4.csv')

In [ ]:
_ = from_smiles(smiles_chunks[5], fingerprints=True, timeout=100, output_csv='drug_descriptors5.csv')

In [ ]:
_ = from_smiles(smiles_chunks[6], fingerprints=True, timeout=100, output_csv='drug_descriptors6.csv')

In [ ]:
_ = from_smiles(smiles_chunks[7], fingerprints=True, timeout=100, output_csv='drug_descriptors7.csv')

In [9]:
Drug_features = pd.read_csv("E://Drug Efficacy project//Data//input to my project//drug features//complete_desciptors.csv")

In [10]:
Drug_features

,PubCHEM,Name,nAcid,ALogP,ALogp2,AMR,apol,naAromAtom,nAromBond,nAtom,...,PubchemFP871,PubchemFP872,PubchemFP873,PubchemFP874,PubchemFP875,PubchemFP876,PubchemFP877,PubchemFP878,PubchemFP879,PubchemFP880
0,25102847,AUTOGEN_20210511133942061_1,0,-1.2926,1.670815,44.3575,73.150032,22,23,61,...,0,0,0,0,0,0,0,0,0,0
1,148124,AUTOGEN_20210511133942061_2,0,-0.8590,0.737881,148.8337,123.348029,12,12,111,...,0,0,0,0,0,0,0,0,0,0
2,5289247,AUTOGEN_20210511133942061_3,0,0.3717,0.138161,29.8239,33.591551,10,11,25,...,0,0,0,0,0,0,0,0,0,0
3,9868037,AUTOGEN_20210511133942061_4,0,1.6315,2.661792,31.6740,58.863688,21,22,47,...,0,0,0,0,0,0,0,0,0,0
4,11364421,AUTOGEN_20210511133942061_5,0,-3.7102,13.765584,88.5111,85.390927,12,12,77,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
218,24978538,AUTOGEN_20210509110644039_9,0,2.9144,8.493727,152.5332,142.256615,24,24,120,...,0,0,0,0,0,0,0,0,0,0
219,10461815,AUTOGEN_20210509110644039_10,0,-0.4041,0.163297,99.8922,93.858962,17,17,77,...,0,0,0,0,0,0,0,0,0,0
220,126565,AUTOGEN_20210509110644039_11,0,-2.0293,4.118058,46.0016,66.270653,20,24,54,...,0,0,0,0,0,0,0,0,0,0
221,446378,AUTOGEN_20210509110644039_12,0,-0.8057,0.649152,154.0814,102.803650,0,0,96,...,0,0,0,0,0,0,0,0,0,0
222,6253,AUTOGEN_20210509110644039_13,0,-2.9200,8.526400,41.5610,32.485102,6,6,31,...,0,0,0,0,0,0,0,0,0,0

In [11]:
Drug_features.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 223 entries, 0 to 222
Columns: 2758 entries, PubCHEM to PubchemFP880
dtypes: float64(1742), int64(1012), object(4)
memory usage: 4.7+ MB

In [12]:
l11 = []
for x in Drug_features.columns:
    
    if Drug_features[x].dtype == object:
        l11.append(x)
print(l11)

['Name', 'VR3_Dt', 'gmin', 'VR3_D']

In [13]:
search = '#Name' 
Drug_features.loc[Drug_features.isin([search]).any(axis=1)].index.tolist()

[]

In [14]:
Drug_features.drop(index =203, inplace = True) # this row or drug was throwing continuous errors , so deleted from drug list

In [15]:
Drug_features["VR3_Dt"] = Drug_features.VR3_Dt.astype(float)

In [16]:
Drug_features["VR3_D"] = Drug_features.VR3_D.astype(float)

In [17]:
Drug_features["gmin"] = Drug_features.gmin.astype(float)
Drug_features.drop(columns = ["Name"], inplace = True)
Drug_features.head()

,PubCHEM,nAcid,ALogP,ALogp2,AMR,apol,naAromAtom,nAromBond,nAtom,nHeavyAtom,...,PubchemFP871,PubchemFP872,PubchemFP873,PubchemFP874,PubchemFP875,PubchemFP876,PubchemFP877,PubchemFP878,PubchemFP879,PubchemFP880
0,25102847,0,-1.2926,1.670815,44.3575,73.150032,22,23,61,37,...,0,0,0,0,0,0,0,0,0,0
1,148124,0,-0.8590,0.737881,148.8337,123.348029,12,12,111,58,...,0,0,0,0,0,0,0,0,0,0
2,5289247,0,0.3717,0.138161,29.8239,33.591551,10,11,25,18,...,0,0,0,0,0,0,0,0,0,0
3,9868037,0,1.6315,2.661792,31.6740,58.863688,21,22,47,31,...,0,0,0,0,0,0,0,0,0,0
4,11364421,0,-3.7102,13.765584,88.5111,85.390927,12,12,77,38,...,0,0,0,0,0,0,0,0,0,0

In [18]:
Drug_features.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 222 entries, 0 to 222
Columns: 2757 entries, PubCHEM to PubchemFP880
dtypes: float64(1745), int64(1012)
memory usage: 4.7 MB

In [19]:

# checking for columns with same value across 223 drugs
same_value =[]
new_features=[]
for x in Drug_features.columns:
    if Drug_features[x].nunique() ==1:
        same_value.append(x)
    else :
        new_features.append(x)

In [20]:
len(new_features)

2213

In [21]:
len(same_value)

544

In [22]:
Drug_features_columns = Drug_features.columns

In [23]:
# checking for any empty columns
l1=[]
l2 =[]
for x in Drug_features.columns:
        if len(Drug_features[x].value_counts()) >0:
           l1.append(x)
        else:
           l2.append(x)
print(len(l1))
print(len(l2))

2757
0

In [24]:
new_Drug_features = Drug_features[new_features]

In [25]:
new_Drug_features

,PubCHEM,nAcid,ALogP,ALogp2,AMR,apol,naAromAtom,nAromBond,nAtom,nHeavyAtom,...,PubchemFP831,PubchemFP833,PubchemFP834,PubchemFP835,PubchemFP840,PubchemFP842,PubchemFP847,PubchemFP860,PubchemFP861,PubchemFP863
0,25102847,0,-1.2926,1.670815,44.3575,73.150032,22,23,61,37,...,0,0,0,0,0,0,0,0,0,0
1,148124,0,-0.8590,0.737881,148.8337,123.348029,12,12,111,58,...,0,0,0,0,0,0,0,0,0,0
2,5289247,0,0.3717,0.138161,29.8239,33.591551,10,11,25,18,...,0,1,0,0,0,0,0,0,0,0
3,9868037,0,1.6315,2.661792,31.6740,58.863688,21,22,47,31,...,0,0,0,0,0,0,0,0,0,0
4,11364421,0,-3.7102,13.765584,88.5111,85.390927,12,12,77,38,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
218,24978538,0,2.9144,8.493727,152.5332,142.256615,24,24,120,65,...,0,0,0,0,0,0,0,0,0,0
219,10461815,0,-0.4041,0.163297,99.8922,93.858962,17,17,77,43,...,0,0,0,0,0,0,0,0,0,0
220,126565,0,-2.0293,4.118058,46.0016,66.270653,20,24,54,33,...,0,1,0,0,0,0,0,0,0,0
221,446378,0,-0.8057,0.649152,154.0814,102.803650,0,0,96,46,...,0,0,0,0,1,0,0,1,1,0
222,6253,0,-2.9200,8.526400,41.5610,32.485102,6,6,31,17,...,0,0,0,0,0,0,0,0,0,0

In [26]:
new_Drug_features.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 222 entries, 0 to 222
Columns: 2213 entries, PubCHEM to PubchemFP863
dtypes: float64(1514), int64(699)
memory usage: 3.7 MB

In [27]:
new_Drug_features = new_Drug_features.replace([np.inf, -np.inf], np.nan)

In [28]:
new_Drug_features.isnull().values.any()

True

In [29]:
new_Drug_features.fillna(0, inplace =True)

In [30]:
new_Drug_features.isnull().values.any()

False

# # adding the GDSC ID to the new_Drug_features dataset and this feature will be needed to merge with res dataset

In [34]:
new_Drug_features

,PubCHEM,nAcid,ALogP,ALogp2,AMR,apol,naAromAtom,nAromBond,nAtom,nHeavyAtom,...,PubchemFP831,PubchemFP833,PubchemFP834,PubchemFP835,PubchemFP840,PubchemFP842,PubchemFP847,PubchemFP860,PubchemFP861,PubchemFP863
0,25102847,0,-1.2926,1.670815,44.3575,73.150032,22,23,61,37,...,0,0,0,0,0,0,0,0,0,0
1,148124,0,-0.8590,0.737881,148.8337,123.348029,12,12,111,58,...,0,0,0,0,0,0,0,0,0,0
2,5289247,0,0.3717,0.138161,29.8239,33.591551,10,11,25,18,...,0,1,0,0,0,0,0,0,0,0
3,9868037,0,1.6315,2.661792,31.6740,58.863688,21,22,47,31,...,0,0,0,0,0,0,0,0,0,0
4,11364421,0,-3.7102,13.765584,88.5111,85.390927,12,12,77,38,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
218,24978538,0,2.9144,8.493727,152.5332,142.256615,24,24,120,65,...,0,0,0,0,0,0,0,0,0,0
219,10461815,0,-0.4041,0.163297,99.8922,93.858962,17,17,77,43,...,0,0,0,0,0,0,0,0,0,0
220,126565,0,-2.0293,4.118058,46.0016,66.270653,20,24,54,33,...,0,1,0,0,0,0,0,0,0,0
221,446378,0,-0.8057,0.649152,154.0814,102.803650,0,0,96,46,...,0,0,0,0,1,0,0,1,1,0
222,6253,0,-2.9200,8.526400,41.5610,32.485102,6,6,31,17,...,0,0,0,0,0,0,0,0,0,0

In [71]:
drug_data = pd.read_csv("E://Drug Efficacy project//Data//modified_Drug_listWed May  5 13_49_34 2021.CSV")
drug_data

,drug_id,Name,Synonyms,Targets,Target pathway,PubCHEM,Sample Size,Count,Unnamed: 8,aa
0,1242,(5Z)-7-Oxozeaenol,"5Z-7-Oxozeaenol, LL-Z1640-2",TAK1,"Other, kinases",9863776,GDSC1,912,SANGER,565
1,179,5-Fluorouracil,5-FU,Antimetabolite (DNA & RNA),Other,3385,GDSC1,913,MGH,565
2,1073,5-Fluorouracil,5-FU,Antimetabolite (DNA & RNA),Other,3385,GDSC2,806,SANGER,565
3,86,A-443654,KIN001-139,"AKT1, AKT2, AKT3",PI3K/MTOR signaling,10172943,GDSC1,399,MGH,565
4,55,A-770041,KIN001-111,"LCK, FYN","Other, kinases",9549184,GDSC1,399,MGH,565
...,...,...,...,...,...,...,...,...,...,...
383,45,Z-LLNle-CHO,"Z-L-Norleucine-CHO, Gamma-Secretase Inhibitor 1",gamma-secretase,Other,16760646,GDSC1,399,MGH,565
384,1050,ZM447439,"ZM-447439, ZM 447439","AURKA, AURKB",Mitosis,9914412,GDSC1,947,SANGER,565
385,1050,ZM447439,"ZM-447439, ZM 447439","AURKA, AURKB",Mitosis,9914412,GDSC2,48,SANGER,565
386,223,ZSTK474,"KIN001-167, ZSTK-474, ZSTK 474",PI3K (class 1),PI3K/MTOR signaling,11647372,GDSC1,917,MGH,565
387,266,Zibotentan,"ZD4054, ZD-4054",Endothelin-1 receptor (EDNRA),Other,9910224,GDSC1,918,MGH,565

In [72]:
drug_data = drug_data[['drug_id','PubCHEM']]
drug_data

     drug_id   PubCHEM
0       1242   9863776
1        179      3385
2       1073      3385
3         86  10172943
4         55   9549184
..       ...       ...
383       45  16760646
384     1050   9914412
385     1050   9914412
386      223  11647372
387      266   9910224

[388 rows x 2 columns]

In [73]:
drug_data.drug_id.nunique(dropna = True)

347

In [74]:
drug_data.PubCHEM.nunique(dropna = True)

303

In [75]:
drug_data = drug_data[drug_data['PubCHEM'].notna()]

In [76]:
drug_data

     drug_id   PubCHEM
0       1242   9863776
1        179      3385
2       1073      3385
3         86  10172943
4         55   9549184
..       ...       ...
383       45  16760646
384     1050   9914412
385     1050   9914412
386      223  11647372
387      266   9910224

[388 rows x 2 columns]

In [78]:
drug_data = drug_data[drug_data['PubCHEM'].notna()]

In [70]:
drug_data

     drug_id   PubCHEM
0       1242   9863776
1        179      3385
2       1073      3385
3         86  10172943
4         55   9549184
..       ...       ...
555       45  16760646
557     1050   9914412
558     1050   9914412
559      223  11647372
560      266   9910224

[390 rows x 2 columns]

In [79]:
drug_data["PubCHEM"] = drug_data.PubCHEM.astype(float)

In [80]:
new_Drug_features["PubCHEM"] = new_Drug_features.PubCHEM.astype(float)

In [81]:
drugs = pd.merge(new_Drug_features, drug_data, on = 'PubCHEM')

In [82]:
drugs

,PubCHEM,nAcid,ALogP,ALogp2,AMR,apol,naAromAtom,nAromBond,nAtom,nHeavyAtom,...,PubchemFP833,PubchemFP834,PubchemFP835,PubchemFP840,PubchemFP842,PubchemFP847,PubchemFP860,PubchemFP861,PubchemFP863,drug_id
0,25102847.0,0,-1.2926,1.670815,44.3575,73.150032,22,23,61,37,...,0,0,0,0,0,0,0,0,0,249
1,148124.0,0,-0.8590,0.737881,148.8337,123.348029,12,12,111,58,...,0,0,0,0,0,0,0,0,0,1007
2,148124.0,0,-0.8590,0.737881,148.8337,123.348029,12,12,111,58,...,0,0,0,0,0,0,0,0,0,1007
3,5289247.0,0,0.3717,0.138161,29.8239,33.591551,10,11,25,18,...,1,0,0,0,0,0,0,0,0,224
4,9868037.0,0,1.6315,2.661792,31.6740,58.863688,21,22,47,31,...,0,0,0,0,0,0,0,0,0,298
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
300,10461815.0,0,-0.4041,0.163297,99.8922,93.858962,17,17,77,43,...,0,0,0,0,0,0,0,0,0,6
301,126565.0,0,-2.0293,4.118058,46.0016,66.270653,20,24,54,33,...,1,0,0,0,0,0,0,0,0,1024
302,446378.0,0,-0.8057,0.649152,154.0814,102.803650,0,0,96,46,...,0,0,0,1,0,0,1,1,0,180
303,6253.0,0,-2.9200,8.526400,41.5610,32.485102,6,6,31,17,...,0,0,0,0,0,0,0,0,0,1006
304,6253.0,0,-2.9200,8.526400,41.5610,32.485102,6,6,31,17,...,0,0,0,0,0,0,0,0,0,1006

In [83]:
drugs.to_csv('E://Drug Efficacy project//Data//drugs_intermediate_checking.CSV', index = False)

In [85]:
# the number of rows in the merged dataset are more because in the drugs_data dataframe their were 
# same PUBCHEM IDS with different drug ID's