In [1]:
import pandas as pd
rna = pd.read_csv("E://Drug Efficacy project//Data//input to my project//modified_rnaseq_fpkm_20191101.csv")

In [2]:
rna.head()

,symbol,MEC-1,NBsusSR,M14,MDA-MB-134-VI,MCC26,MCC13,MCAS,MC-1010,Malme-3M,...,MMAc-SF,BE-13,MC-IXC,Ramos-2G6-4C10,CGTH-W-1,H9,P3HR-1,HUH-6-clone5,GR-ST,MM1S
0,A1BG,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,A1BG-AS1,0.0,1.0,3.0,2.0,2.0,4.0,0.0,4.0,2.0,...,4.0,2.0,2.0,6.0,3.0,0.0,0.0,0.0,4.0,0.0
2,A1CF,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0
3,A2M,0.0,0.0,8.0,0.0,23.0,0.0,0.0,0.0,90.0,...,8.0,0.0,1.0,0.0,0.0,0.0,0.0,13.0,0.0,0.0
4,A2M-AS1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [3]:
rna.fillna(value = 0, inplace = True)

In [4]:
percent_missing = rna.isnull().sum() * 100 / len(rna)
missing_value_df = pd.DataFrame({'column_name': rna.columns,
                                 'percent_missing': percent_missing})

In [5]:
missing_value_df.sort_values('percent_missing', inplace=True)

In [6]:
missing_value_df

         column_name  percent_missing
symbol        symbol              0.0
RCC-ER        RCC-ER              0.0
RCC-AB        RCC-AB              0.0
COLO-201    COLO-201              0.0
COLO-205    COLO-205              0.0
...              ...              ...
MOLT-13      MOLT-13              0.0
MOLP-8        MOLP-8              0.0
MOLM-16      MOLM-16              0.0
MN-60          MN-60              0.0
MM1S            MM1S              0.0

[1048 rows x 2 columns]

In [7]:
rna_t = rna.T

In [8]:
rna_t

,0,1,2,3,4,5,6,7,8,9,...,37269,37270,37271,37272,37273,37274,37275,37276,37277,37278
symbol,A1BG,A1BG-AS1,A1CF,A2M,A2M-AS1,A2ML1,A2ML1-AS1,A2ML1-AS2,A2MP1,A3GALT2,...,ZXDA,ZXDB,ZXDC,ZYG11A,ZYG11AP1,ZYG11B,ZYX,ZYXP1,ZZEF1,ZZZ3
MEC-1,0,0,0,0,0,0,0,0,0,0,...,0,2,2,0,0,2,8,0,3,4
NBsusSR,0,1,0,0,0,0,0,0,0,0,...,1,3,15,0,0,8,15,0,6,12
M14,0,3,0,8,0,0,0,0,0,0,...,0,2,4,3,0,8,51,0,7,12
MDA-MB-134-VI,0,2,0,0,1,0,0,2,0,0,...,1,2,7,1,0,3,6,0,3,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
H9,0,0,0,0,0,0,0,0,0,0,...,3,7,10,5,0,4,44,0,18,6
P3HR-1,0,0,0,0,0,0,0,0,0,0,...,0,0,3,0,0,2,1,0,9,6
HUH-6-clone5,0,0,5,13,0,0,0,0,0,0,...,0,2,8,2,0,4,19,0,2,8
GR-ST,0,4,0,0,0,0,0,0,0,0,...,1,6,14,0,0,7,8,0,20,15
MM1S,0,0,0,0,0,0,0,0,0,0,...,0,1,6,1,0,3,11,0,8,6

In [9]:
rna_t.columns

RangeIndex(start=0, stop=37279, step=1)

In [10]:
rna_t.columns=rna_t.iloc[0]

In [11]:
rna_t= rna_t.iloc[1:,:]

In [12]:
rna_t

symbol,A1BG,A1BG-AS1,A1CF,A2M,A2M-AS1,A2ML1,A2ML1-AS1,A2ML1-AS2,A2MP1,A3GALT2,...,ZXDA,ZXDB,ZXDC,ZYG11A,ZYG11AP1,ZYG11B,ZYX,ZYXP1,ZZEF1,ZZZ3
MEC-1,0,0,0,0,0,0,0,0,0,0,...,0,2,2,0,0,2,8,0,3,4
NBsusSR,0,1,0,0,0,0,0,0,0,0,...,1,3,15,0,0,8,15,0,6,12
M14,0,3,0,8,0,0,0,0,0,0,...,0,2,4,3,0,8,51,0,7,12
MDA-MB-134-VI,0,2,0,0,1,0,0,2,0,0,...,1,2,7,1,0,3,6,0,3,7
MCC26,0,2,0,23,0,0,0,0,0,0,...,0,2,4,4,0,7,141,0,3,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
H9,0,0,0,0,0,0,0,0,0,0,...,3,7,10,5,0,4,44,0,18,6
P3HR-1,0,0,0,0,0,0,0,0,0,0,...,0,0,3,0,0,2,1,0,9,6
HUH-6-clone5,0,0,5,13,0,0,0,0,0,0,...,0,2,8,2,0,4,19,0,2,8
GR-ST,0,4,0,0,0,0,0,0,0,0,...,1,6,14,0,0,7,8,0,20,15
MM1S,0,0,0,0,0,0,0,0,0,0,...,0,1,6,1,0,3,11,0,8,6

In [13]:
y = rna_t.index

In [14]:
y

Index(['MEC-1', 'NBsusSR', 'M14', 'MDA-MB-134-VI', 'MCC26', 'MCC13', 'MCAS',
       'MC-1010', 'Malme-3M', 'LIM1215',
       ...
       'MMAc-SF', 'BE-13', 'MC-IXC', 'Ramos-2G6-4C10', 'CGTH-W-1', 'H9',
       'P3HR-1', 'HUH-6-clone5', 'GR-ST', 'MM1S'],
      dtype='object', length=1047)

In [15]:
rna_t.insert(0, 'CELL_LINE_NAME', y)

In [16]:
rna_t

symbol,CELL_LINE_NAME,A1BG,A1BG-AS1,A1CF,A2M,A2M-AS1,A2ML1,A2ML1-AS1,A2ML1-AS2,A2MP1,...,ZXDA,ZXDB,ZXDC,ZYG11A,ZYG11AP1,ZYG11B,ZYX,ZYXP1,ZZEF1,ZZZ3
MEC-1,MEC-1,0,0,0,0,0,0,0,0,0,...,0,2,2,0,0,2,8,0,3,4
NBsusSR,NBsusSR,0,1,0,0,0,0,0,0,0,...,1,3,15,0,0,8,15,0,6,12
M14,M14,0,3,0,8,0,0,0,0,0,...,0,2,4,3,0,8,51,0,7,12
MDA-MB-134-VI,MDA-MB-134-VI,0,2,0,0,1,0,0,2,0,...,1,2,7,1,0,3,6,0,3,7
MCC26,MCC26,0,2,0,23,0,0,0,0,0,...,0,2,4,4,0,7,141,0,3,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
H9,H9,0,0,0,0,0,0,0,0,0,...,3,7,10,5,0,4,44,0,18,6
P3HR-1,P3HR-1,0,0,0,0,0,0,0,0,0,...,0,0,3,0,0,2,1,0,9,6
HUH-6-clone5,HUH-6-clone5,0,0,5,13,0,0,0,0,0,...,0,2,8,2,0,4,19,0,2,8
GR-ST,GR-ST,0,4,0,0,0,0,0,0,0,...,1,6,14,0,0,7,8,0,20,15
MM1S,MM1S,0,0,0,0,0,0,0,0,0,...,0,1,6,1,0,3,11,0,8,6

In [17]:
# reducing the dataframes memory by converting the columns--reduced from 298mb to 37 mb

In [18]:
rna_t.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1047 entries, MEC-1 to MM1S
Columns: 37280 entries, CELL_LINE_NAME to ZZZ3
dtypes: object(37280)
memory usage: 297.8+ MB

In [19]:
y = rna_t['CELL_LINE_NAME']
rna_t.drop(columns =['CELL_LINE_NAME'], inplace =True)

C:\Users\vivek\anaconda3\lib\site-packages\pandas\core\frame.py:3990: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

In [20]:
rna_t

symbol,A1BG,A1BG-AS1,A1CF,A2M,A2M-AS1,A2ML1,A2ML1-AS1,A2ML1-AS2,A2MP1,A3GALT2,...,ZXDA,ZXDB,ZXDC,ZYG11A,ZYG11AP1,ZYG11B,ZYX,ZYXP1,ZZEF1,ZZZ3
MEC-1,0,0,0,0,0,0,0,0,0,0,...,0,2,2,0,0,2,8,0,3,4
NBsusSR,0,1,0,0,0,0,0,0,0,0,...,1,3,15,0,0,8,15,0,6,12
M14,0,3,0,8,0,0,0,0,0,0,...,0,2,4,3,0,8,51,0,7,12
MDA-MB-134-VI,0,2,0,0,1,0,0,2,0,0,...,1,2,7,1,0,3,6,0,3,7
MCC26,0,2,0,23,0,0,0,0,0,0,...,0,2,4,4,0,7,141,0,3,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
H9,0,0,0,0,0,0,0,0,0,0,...,3,7,10,5,0,4,44,0,18,6
P3HR-1,0,0,0,0,0,0,0,0,0,0,...,0,0,3,0,0,2,1,0,9,6
HUH-6-clone5,0,0,5,13,0,0,0,0,0,0,...,0,2,8,2,0,4,19,0,2,8
GR-ST,0,4,0,0,0,0,0,0,0,0,...,1,6,14,0,0,7,8,0,20,15
MM1S,0,0,0,0,0,0,0,0,0,0,...,0,1,6,1,0,3,11,0,8,6

In [21]:
rna_t.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1047 entries, MEC-1 to MM1S
Columns: 37279 entries, A1BG to ZZZ3
dtypes: object(37279)
memory usage: 297.8+ MB

In [22]:
import numpy as np
for p in rna_t.columns:
    
    rna_t[p] = rna_t[p].astype(np.uint8)

<ipython-input-22-0ac13c93f90f>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rna_t[p] = rna_t[p].astype(np.uint8)

In [23]:
rna_t.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1047 entries, MEC-1 to MM1S
Columns: 37279 entries, A1BG to ZZZ3
dtypes: uint8(37279)
memory usage: 37.2+ MB

In [24]:
rna_t.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1047 entries, MEC-1 to MM1S
Columns: 37279 entries, A1BG to ZZZ3
dtypes: uint8(37279)
memory usage: 37.2+ MB

In [25]:
rna_t.insert(0,"CELL_LINE_NAME", y)

In [26]:
rna_t

symbol,CELL_LINE_NAME,A1BG,A1BG-AS1,A1CF,A2M,A2M-AS1,A2ML1,A2ML1-AS1,A2ML1-AS2,A2MP1,...,ZXDA,ZXDB,ZXDC,ZYG11A,ZYG11AP1,ZYG11B,ZYX,ZYXP1,ZZEF1,ZZZ3
MEC-1,MEC-1,0,0,0,0,0,0,0,0,0,...,0,2,2,0,0,2,8,0,3,4
NBsusSR,NBsusSR,0,1,0,0,0,0,0,0,0,...,1,3,15,0,0,8,15,0,6,12
M14,M14,0,3,0,8,0,0,0,0,0,...,0,2,4,3,0,8,51,0,7,12
MDA-MB-134-VI,MDA-MB-134-VI,0,2,0,0,1,0,0,2,0,...,1,2,7,1,0,3,6,0,3,7
MCC26,MCC26,0,2,0,23,0,0,0,0,0,...,0,2,4,4,0,7,141,0,3,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
H9,H9,0,0,0,0,0,0,0,0,0,...,3,7,10,5,0,4,44,0,18,6
P3HR-1,P3HR-1,0,0,0,0,0,0,0,0,0,...,0,0,3,0,0,2,1,0,9,6
HUH-6-clone5,HUH-6-clone5,0,0,5,13,0,0,0,0,0,...,0,2,8,2,0,4,19,0,2,8
GR-ST,GR-ST,0,4,0,0,0,0,0,0,0,...,1,6,14,0,0,7,8,0,20,15
MM1S,MM1S,0,0,0,0,0,0,0,0,0,...,0,1,6,1,0,3,11,0,8,6

In [27]:
# saving this dataset to pickle, the above step took almosta 5 hours of processing..henec better to use 
#the pickle file (rna.pickle)

In [28]:
import pickle

In [29]:
pickle_out = open("rna.pickle", "wb")

In [30]:
pickle.dump(rna_t,pickle_out)
pickle_out.close()