<a href="https://colab.research.google.com/github/mevivekmevivek/Drug-Efficacy-Prediction/blob/main/STR%26SNP_Predictions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
#!unzip /content/GDSC1_fitted_dose_response_25Feb20.zip

new_gdsc = pd.read_csv('/content/GDSC1_fitted_dose_response_25Feb20.csv')

In [ ]:
new_gdsc

       DATASET  NLME_RESULT_ID  NLME_CURVE_ID  ...       AUC      RMSE   Z_SCORE
0        GDSC1             281       12974350  ...  0.982114  0.022521 -0.189576
1        GDSC1             281       12975300  ...  0.984816  0.031840  0.508635
2        GDSC1             281       12975647  ...  0.985693  0.026052  1.284229
3        GDSC1             281       12975980  ...  0.972699  0.110056  0.088760
4        GDSC1             281       12976330  ...  0.944462  0.087011 -0.111820
...        ...             ...            ...  ...       ...       ...       ...
310899   GDSC1             281       13269726  ...  0.975376  0.032752  0.299720
310900   GDSC1             281       13269986  ...  0.977001  0.040082  1.742423
310901   GDSC1             281       13270253  ...  0.979140  0.042595  1.155838
310902   GDSC1             281       13270519  ...  0.982310  0.038664  0.716003
310903   GDSC1             281       13270784  ...  0.975279  0.076326 -0.340255

[310904 rows x 19 columns]

In [ ]:
from google.colab import files
#uploaded = files.upload()
#gdsc_IC50 = pd.read_csv("E://Drug Efficacy project//Data//GDSC1_fitted_dose_response_25Feb20.csv")
import io

# cell lines are represented by STR, SNP and MSI details published by GDSC concatinated
#cellines = pd.read_csv(io.BytesIO(uploaded['Annotations_modified.csv'])) 
cellines = pd.read_csv('Annotations_modified.csv')

In [ ]:
# using the encoded drug fetaure (reduced dimensions from 2500 to 50 using autoencoders)
# earlier 'complete_desciptors - Copy.csv' was used
!unzip /content/final_drug_encoded.zip

drug_encoded = pd.read_csv('/content/final_drug_encoded.zip')

Archive:  /content/final_drug_encoded.zip
replace final_drug_encoded.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: final_drug_encoded.csv

In [ ]:
drug_encoded

      PubChem  drug_id  ...  drug_feature_48  drug_feature_49
0    25102847      249  ...        -2.414763         4.244452
1      148124     1007  ...         2.147692         4.439437
2     5289247      224  ...        -4.258195        -1.275436
3     9868037      298  ...        -2.618290        -0.690906
4    11364421       60  ...        -2.241937        -2.626314
..        ...      ...  ...              ...              ...
218  24978538     1011  ...         7.009082        -1.639581
219  10461815        6  ...        -3.223059        -5.100493
220    126565     1024  ...        -5.698654        -1.557533
221    446378      180  ...         1.892492        -5.466690
222      6253     1006  ...        -5.183023       -11.858224

[223 rows x 52 columns]

In [ ]:
# from google.colab import files
# uploaded = files.upload()
# import io
# drug_features = pd.read_csv(io.BytesIO(uploaded['complete_desciptors - Copy.csv']))
# #drug_features = pd.read_csv(io.BytesIO(uploaded['complete_desciptors.csv']))


# after checking the final performance metrics for all the models using the encoded drug fetaures
# checking the model performance using non encoded fetaures
#!unzip /content/complete_desciptors.zip
drugs = pd.read_csv('/content/complete_desciptors.csv')

In [ ]:
new_gdsc= new_gdsc[['COSMIC_ID', 'DRUG_ID','MIN_CONC','MAX_CONC', 'LN_IC50', "COMPANY_ID"]]

In [ ]:
# in the gdsc file, their are 345 unique drug names , but when we check with the drug_id, their are
# 367 unique drug id's, so that implies for some drugs the id's are different but the names are same
# for our project we are taking each unique drug id as a new drug, so we are considering 367 drugs

In [ ]:
new_gdsc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 310904 entries, 0 to 310903
Data columns (total 6 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   COSMIC_ID   310904 non-null  int64
 1   DRUG_ID     310904 non-null  int64
 2   MIN_CONC    310904 non-null  float64
 3   MAX_CONC    310904 non-null  float64
 4   LN_IC50     310904 non-null  float64
 5   COMPANY_ID  310904 non-null  int64
dtypes: float64(3), int64(3)
memory usage: 14.2 MB

In [ ]:
import numpy as np
for i in new_gdsc.columns:
    if(new_gdsc[i].dtype == np.float64):
          new_gdsc[i] = new_gdsc[i].astype('float16')

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.

In [ ]:
new_gdsc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 310904 entries, 0 to 310903
Data columns (total 6 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   COSMIC_ID   310904 non-null  int64
 1   DRUG_ID     310904 non-null  int64
 2   MIN_CONC    310904 non-null  float16
 3   MAX_CONC    310904 non-null  float16
 4   LN_IC50     310904 non-null  float16
 5   COMPANY_ID  310904 non-null  int64
dtypes: float16(3), int64(3)
memory usage: 8.9 MB

In [ ]:

#cellines = pd.read_csv("E://Drug Efficacy project//Data//input to my project//Annotations_modified.csv")

In [ ]:
cellines = pd.read_csv('Annotations_modified.csv')

In [ ]:
cellines.rename(columns= {'COSMIC ID':'COSMIC_ID'}, inplace = True)

In [ ]:
cellines.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 976 entries, 0 to 975
Columns: 130 entries, Line to D5S346
dtypes: float64(6), int64(19), object(105)
memory usage: 991.4+ KB

In [ ]:
response_new = pd.merge(new_gdsc, cellines, on='COSMIC_ID')

In [ ]:
response_new

        COSMIC_ID  DRUG_ID  MIN_CONC   MAX_CONC  ...   BAT26  D17S250  D2S123  D5S346
0          683665        1  0.007812   2.000000  ...  stable   stable  stable  stable
1          683665        3  0.000391   0.099976  ...  stable   stable  stable  stable
2          683665        5  0.031250   8.000000  ...  stable   stable  stable  stable
3          683665        6  0.007812   2.000000  ...  stable   stable  stable  stable
4          683665        9  0.003906   1.000000  ...  stable   stable  stable  stable
...           ...      ...       ...        ...  ...     ...      ...     ...     ...
298840    1322212     1502  0.039062  10.000000  ...  stable   stable  stable  stable
298841    1322212     1526  0.019531   5.000000  ...  stable   stable  stable  stable
298842    1322212     1527  0.015625   4.000000  ...  stable   stable  stable  stable
298843    1322212     1529  0.003906   1.000000  ...  stable   stable  stable  stable
298844    1322212     1530  0.039062  10.000000  ...  stable   stable  stable  stable

[298845 rows x 135 columns]

In [ ]:
response_new.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 298845 entries, 0 to 298844
Columns: 135 entries, COSMIC_ID to D5S346
dtypes: float16(3), float64(6), int64(21), object(105)
memory usage: 305.0+ MB

# CREATING THE DRUGS DATASET

In [ ]:
# ignoring this part for now because, the processed drug data has been imported
# in the initial stages of the project, we had to perform this, but we have the best drug drug data

In [ ]:
drug_features = drugs.copy()
drug_features

      PubCHEM                          Name  ...  PubchemFP879  PubchemFP880
0    25102847   AUTOGEN_20210511133942061_1  ...             0             0
1      148124   AUTOGEN_20210511133942061_2  ...             0             0
2     5289247   AUTOGEN_20210511133942061_3  ...             0             0
3     9868037   AUTOGEN_20210511133942061_4  ...             0             0
4    11364421   AUTOGEN_20210511133942061_5  ...             0             0
..        ...                           ...  ...           ...           ...
218  24978538   AUTOGEN_20210509110644039_9  ...             0             0
219  10461815  AUTOGEN_20210509110644039_10  ...             0             0
220    126565  AUTOGEN_20210509110644039_11  ...             0             0
221    446378  AUTOGEN_20210509110644039_12  ...             0             0
222      6253  AUTOGEN_20210509110644039_13  ...             0             0

[223 rows x 2759 columns]

In [ ]:
drug_features.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 223 entries, 0 to 222
Columns: 2759 entries, PubCHEM to PubchemFP880
dtypes: float64(1744), int64(1013), object(2)
memory usage: 4.7+ MB

In [ ]:
l11 = []
for x in drug_features.columns:
    
    if drug_features[x].dtype == object:
        l11.append(x)
print(l11)

['Name', 'gmin']

In [ ]:
#drug_features.drop(index =203, inplace = True) # this row or drug was throwing continuous errors , so deleted from drug list

In [ ]:
drug_features["VR3_Dt"] = drug_features.VR3_Dt.astype(float)

In [ ]:
drug_features["VR3_D"] = drug_features.VR3_D.astype(float)

In [ ]:
drug_features["gmin"] = drug_features.gmin.astype(float)
drug_features.drop(columns = ["Name"], inplace = True)
drug_features.head()

    PubCHEM  DRUG_ID  nAcid  ...  PubchemFP878  PubchemFP879  PubchemFP880
0  25102847      249      0  ...             0             0             0
1    148124     1007      0  ...             0             0             0
2   5289247      224      0  ...             0             0             0
3   9868037      298      0  ...             0             0             0
4  11364421       60      0  ...             0             0             0

[5 rows x 2758 columns]

In [ ]:
drug_features.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 223 entries, 0 to 222
Columns: 2758 entries, PubCHEM to PubchemFP880
dtypes: float64(1745), int64(1013)
memory usage: 4.7 MB

In [ ]:

# checking for columns with same value across 223 drugs
same_value =[]
new_features=[]
for x in drug_features.columns:
    if drug_features[x].nunique() ==1:
        same_value.append(x)
    else :
        new_features.append(x)

In [ ]:
len(new_features)

2219

In [ ]:
len(same_value)

539

In [ ]:
Drug_features_columns = drug_features.columns

In [ ]:
# checking for any empty columns
l1=[]
l2 =[]
for x in drug_features.columns:
        if len(drug_features[x].value_counts()) >0:
           l1.append(x)
        else:
           l2.append(x)
print(len(l1))
print(len(l2))

2758
0

In [ ]:
new_Drug_features = drug_features[new_features]

In [ ]:
new_Drug_features = new_Drug_features.replace([np.inf, -np.inf], np.nan)

In [ ]:
new_Drug_features.isnull().values.any()

True

In [ ]:
new_Drug_features.fillna(0, inplace =True)

In [ ]:
new_Drug_features.isnull().values.any()

False

In [ ]:
#new_Drug_features = drug_encoded
#new_Drug_features.drop(columns =['PubCHEM'], inplace = True)

In [ ]:
new_Drug_features.rename(columns =({'drug_id': 'DRUG_ID'}), inplace = True)
new_Drug_features.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 223 entries, 0 to 222
Columns: 2219 entries, PubCHEM to PubchemFP863
dtypes: float64(1514), int64(705)
memory usage: 3.8 MB

In [ ]:
full_data = pd.merge(response_new, new_Drug_features, on='DRUG_ID')

In [ ]:
#missing = full_data.isnull().sum() * 100 / len(full_data)
#missing_df = pd.DataFrame({'column_name': full_data.columns,
#                                 'percent_missing': missing})

full_data

        COSMIC_ID  DRUG_ID  MIN_CONC  ...  PubchemFP860  PubchemFP861  PubchemFP863
0          683665        1  0.007812  ...             0             0             0
1          684055        1  0.007812  ...             0             0             0
2          684057        1  0.007812  ...             0             0             0
3          684059        1  0.007812  ...             0             0             0
4          684062        1  0.007812  ...             0             0             0
...           ...      ...       ...  ...           ...           ...           ...
175159    1330948     1530  0.039062  ...             0             0             0
175160    1503364     1530  0.039062  ...             0             0             0
175161    1509073     1530  0.039062  ...             0             0             0
175162    1789883     1530  0.039062  ...             0             0             0
175163    1322212     1530  0.039062  ...             0             0             0

[175164 rows x 2353 columns]

In [ ]:
#missing_df.sort_values('percent_missing', inplace=True)
#missing_df

In [ ]:
catogorical_col = []
numeric_col =[]
for i in full_data.columns:
    if(full_data[i].dtype == np.float64):
        numeric_col.append(i)
    elif (full_data[i].dtype == np.int64):
        numeric_col.append(i)
    elif (full_data[i].dtype == np.float16):
        numeric_col.append(i)
    
    else:
        print(i ,':',len(full_data[i].unique()) )
        
        catogorical_col.append(i)

Line : 948
GS34251 : 3
GS35205 : 4
GS35219 : 3
GS35220 : 3
rs11096957 : 4
rs1131498 : 4
rs12828016 : 4
rs156697 : 4
rs1801262 : 4
rs1805034 : 4
rs1805087 : 4
rs2241714 : 4
rs2247870 : 4
rs2286963 : 4
rs3742207 : 4
rs3795677 : 4
rs4075254 : 4
rs4619 : 4
rs4843075 : 4
rs4925 : 4
rs5215 : 4
rs532841 : 4
rs6166 : 4
rs649058 : 4
rs6557634 : 4
rs6759892 : 4
rs7298565 : 4
rs753381 : 4
rs7627615 : 4
rs8065080 : 4
rs1032807 : 4
rs1074042 : 4
rs1074553 : 4
rs1079820 : 4
rs1105176 : 4
rs1426003 : 4
rs1515002 : 4
rs1541290 : 4
rs156318 : 4
rs1585676 : 4
rs1843026 : 4
rs1952161 : 4
rs2077774 : 4
rs210310 : 4
rs2207782 : 4
rs2361128 : 4
rs2374061 : 4
rs2887851 : 4
rs310929 : 4
rs621277 : 4
rs718757 : 4
rs725029 : 4
rs727081 : 4
rs727336 : 4
rs754257 : 4
rs756497 : 4
rs803172 : 4
rs890910 : 4
rs951629 : 4
rs952503 : 4
rs965323 : 4
rs967344 : 4
rs978422 : 4
rs995553 : 4
rs999072 : 4
rs1030687 : 4
rs1293153 : 4
rs1327118 : 4
rs1363333 : 4
rs1368136 : 4
rs1392265 : 4
rs1395936 : 4
rs1402695 : 4
rs1414904 : 4
rs1541836 : 4
rs171953 : 4
rs1812642 : 4
rs1862456 : 4
rs1928045 : 4
rs1961416 : 4
rs2016588 : 4
rs2077743 : 4
rs2216629 : 4
rs2369898 : 4
rs349235 : 4
rs3904872 : 4
rs502843 : 4
rs522073 : 4
rs719601 : 4
rs722952 : 4
rs726957 : 4
rs728189 : 4
rs763553 : 4
rs894240 : 4
rs952725 : 4
rs952768 : 4
rs958388 : 4
AMEL-A : 3
AMEL-B : 3
BAT25 : 3
BAT26 : 3
D17S250 : 3
D2S123 : 3
D5S346 : 3

In [ ]:
full_data.drop(columns =['Line'], inplace = True)

In [ ]:
catogorical_col= catogorical_col[1:]

len(catogorical_col)

104

In [ ]:
new_df = full_data[(catogorical_col)]

new_df.insert(0,'COSMIC_ID', full_data['COSMIC_ID'])

In [ ]:
new_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 175164 entries, 0 to 175163
Columns: 105 entries, COSMIC_ID to D5S346
dtypes: int64(1), object(104)
memory usage: 141.7+ MB

In [ ]:
new_df =pd.get_dummies(new_df,drop_first = True)

new_df.shape

(175164, 303)

In [ ]:
#new_df_num.info()

In [ ]:
new_df_num = full_data[(numeric_col)]

new_df_num

        COSMIC_ID  DRUG_ID  MIN_CONC  ...  PubchemFP860  PubchemFP861  PubchemFP863
0          683665        1  0.007812  ...             0             0             0
1          684055        1  0.007812  ...             0             0             0
2          684057        1  0.007812  ...             0             0             0
3          684059        1  0.007812  ...             0             0             0
4          684062        1  0.007812  ...             0             0             0
...           ...      ...       ...  ...           ...           ...           ...
175159    1330948     1530  0.039062  ...             0             0             0
175160    1503364     1530  0.039062  ...             0             0             0
175161    1509073     1530  0.039062  ...             0             0             0
175162    1789883     1530  0.039062  ...             0             0             0
175163    1322212     1530  0.039062  ...             0             0             0

[175164 rows x 2248 columns]

In [ ]:
#new_df_num['Reference_ID'] =new_df_num['DRUG_ID'].astype(str)+ '_'+ new_df_num['COSMIC_ID'].astype(str)

In [ ]:
#new_df_num['Reference_ID']

In [ ]:
#new_df_num = new_df_num.drop(columns =['COSMIC_ID'], inplace = True)
new_data = pd.concat( [new_df_num,new_df], axis =1)

In [ ]:
#new_data.info()

In [ ]:
#new_data['Reference_ID']

In [ ]:
y = new_data['LN_IC50']
new_data.drop(columns =['LN_IC50', 'COSMIC_ID',	'DRUG_ID',	'COMPANY_ID'], inplace = True)

In [ ]:
new_data =new_data[~new_data.isin([np.nan, np.inf, -np.inf]).any(1)]

In [ ]:
new_data

        MIN_CONC  MAX_CONC  ...  D5S346_stable  D5S346_unstable
0       0.007812       2.0  ...              1                0
1       0.007812       2.0  ...              1                0
2       0.007812       2.0  ...              1                0
3       0.007812       2.0  ...              1                0
4       0.007812       2.0  ...              1                0
...          ...       ...  ...            ...              ...
175159  0.039062      10.0  ...              1                0
175160  0.039062      10.0  ...              1                0
175161  0.039062      10.0  ...              1                0
175162  0.039062      10.0  ...              1                0
175163  0.039062      10.0  ...              1                0

[175164 rows x 2546 columns]

# Dimensionality Reduction

In [ ]:
from numpy.random import seed
from sklearn.preprocessing import minmax_scale
from sklearn.model_selection import train_test_split
from tensorflow import keras 
from tensorflow.keras.layers import Input, Dense
from tensorflow.keras.models import Model

In [ ]:
new_data_scaled = minmax_scale(new_data, axis = 0)

/usr/local/lib/python3.7/dist-packages/numpy/core/fromnumeric.py:87: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
/usr/local/lib/python3.7/dist-packages/numpy/core/fromnumeric.py:87: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
/usr/local/lib/python3.7/dist-packages/numpy/core/fromnumeric.py:87: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)

In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(new_data_scaled, y, train_size = 0.9, random_state = seed(2017))

In [ ]:
encoding_dim = 150

In [ ]:
from tensorflow.keras.layers import LeakyReLU
ncol = new_data_scaled.shape[1]
input_dim = Input(shape = (ncol, ))

# Encoder Layers


encoded4 = Dense(encoding_dim)(input_dim)
encoded4= LeakyReLU(alpha=0.3)(encoded4)


encoder_1 = Model(input_dim, encoded4, name ='encoder_1')

# Decoder Layers
decoded4 = Dense(ncol, activation = 'relu')(encoded4)

# Combine Encoder and Deocder layers
autoencoder = Model(inputs = input_dim, outputs = decoded4)

# Compile the Model
autoencoder.compile(optimizer = 'adam', loss = 'mae')

In [ ]:
autoencoder.summary()

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
input_1 (InputLayer)         [(None, 2546)]            0
_________________________________________________________________
dense (Dense)                (None, 150)               382050
_________________________________________________________________
leaky_re_lu (LeakyReLU)      (None, 150)               0
_________________________________________________________________
dense_1 (Dense)              (None, 2546)              384446
=================================================================
Total params: 766,496
Trainable params: 766,496
Non-trainable params: 0
_________________________________________________________________

In [ ]:
#!pip3 install tensorflow==2.0.0b1

In [ ]:
#autoencoder.fit(X_train, X_train, epochs = 20, batch_size = 15, shuffle = False, validation_data = (X_test, X_test))

In [ ]:
encoded_input = Input(shape = (encoding_dim, ))
encoded_train_1 = pd.DataFrame(encoder_1.predict(new_data_scaled))
encoded_train_1 = encoded_train_1.add_prefix('new_feature_')

In [ ]:
encoded_train_1_columns = encoded_train_1.columns
encoded_train_1_columns

In [ ]:

#encoded_train_columns = encoded_train.columns
for l in encoded_train_1_columns:
  if (encoded_train_1[l] == 0).all():
    print("TRUE", l)

In [ ]:
encoded_train_1

# Stacked Regression from the final model

In [ ]:
new_data

        MIN_CONC  MAX_CONC  ...  D5S346_stable  D5S346_unstable
0       0.007812       2.0  ...              1                0
1       0.007812       2.0  ...              1                0
2       0.007812       2.0  ...              1                0
3       0.007812       2.0  ...              1                0
4       0.007812       2.0  ...              1                0
...          ...       ...  ...            ...              ...
175159  0.039062      10.0  ...              1                0
175160  0.039062      10.0  ...              1                0
175161  0.039062      10.0  ...              1                0
175162  0.039062      10.0  ...              1                0
175163  0.039062      10.0  ...              1                0

[175164 rows x 2546 columns]

In [ ]:
y 
#new_data.drop(columns =['LN_IC50'], inplace = True)

0         2.396484
1         3.140625
2         3.968750
3         2.693359
4         2.478516
            ...
175159    3.669922
175160    4.605469
175161    4.851562
175162    4.390625
175163    4.562500
Name: LN_IC50, Length: 175164, dtype: float16

In [ ]:
from sklearn.model_selection import train_test_split

train_data, test_data, train_ic50, test_ic50 = train_test_split( new_data, y, test_size=1/10, random_state=0)

In [ ]:

from sklearn.linear_model import ElasticNet, Lasso
from sklearn.model_selection import KFold, cross_val_score
import xgboost
from xgboost import plot_importance
from collections import OrderedDict
lasso = Lasso(alpha =0.0005)
model = xgboost.XGBRegressor(tree_method='gpu_hist',colsample_bytree=0.4,
                 gamma=0,                 
                 learning_rate=0.07,
                 max_depth=9,
                 min_child_weight=1.5,
                 n_estimators=2000,                                                                    
                 reg_alpha=0.75,
                 reg_lambda=0.45,
                 subsample=0.6,
                 seed=42
                 )

In [ ]:
!pip install xgboost

Requirement already satisfied: xgboost in /usr/local/lib/python3.7/dist-packages (0.90)
Requirement already satisfied: numpy in /usr/local/lib/python3.7/dist-packages (from xgboost) (1.19.5)
Requirement already satisfied: scipy in /usr/local/lib/python3.7/dist-packages (from xgboost) (1.4.1)

In [ ]:
#m1 = xgboost.XGBRegressor(tree_method='gpu_hist')

In [ ]:
model.fit(train_data, train_ic50)

In [ ]:
from sklearn.metrics import mean_squared_error,auc

def mse(y, y_pred):
    return mean_squared_error(y, y_pred)

In [ ]:
y =model.predict(test_data)
mse(test_ic50, y)

In [ ]:
from sklearn.model_selection import KFold, cross_val_score
from sklearn.model_selection import cross_validate

n_folds = 5 # number of folds
def get_cv_scores(model, X, y, print_scores=True):
    kf = KFold(n_folds, shuffle=True, random_state=42).get_n_splits(X) # create folds
    scores = cross_validate(model, X, y, cv=kf,
                         scoring=('r2', 'neg_mean_squared_error'),
                         return_train_score=True)
      
    #rmse = -cross_val_score(model, X, y, scoring="neg_mean_squared_error", cv = kf) # get rmse
    #r2 = cross_val_score(model, X, y, scoring="r2", cv = kf) # get rmse
    if print_scores:
      print(scores['test_neg_mean_squared_error'], "Mean MSE :",scores['test_neg_mean_squared_error'].mean())
      print(scores['test_r2'], "Mean R2 :",scores['test_r2'].mean())
    #     print(f'Root mean squared error: {rmse.mean():.3f} ({rmse.std():.3f})')
    #     print(f'R2: {r2.mean():.3f} ({r2.std():.3f})')
    return scores

In [ ]:
get_cv_scores(model,train_data, train_ic50)

[14:21:19] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[14:26:30] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[14:31:38] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[14:36:47] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[14:42:00] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[-1.45111847 -1.44312978 -1.44285274 -1.44683909 -1.44833064] Mean MSE : -1.44645414352417
[0.80685563 0.80898872 0.80982369 0.81029037 0.80773676] Mean R2 : 0.8087390344349897

{'fit_time': array([281.01699638, 280.17516208, 280.86042047, 283.3502779 ,
        285.05071354]),
 'score_time': array([2.79159856, 4.01311898, 4.1632998 , 3.96272683, 3.81053925]),
 'test_neg_mean_squared_error': array([-1.45111847, -1.44312978, -1.44285274, -1.44683909, -1.44833064]),
 'test_r2': array([0.80685563, 0.80898872, 0.80982369, 0.81029037, 0.80773676]),
 'train_neg_mean_squared_error': array([-0.04488971, -0.04422067, -0.04465743, -0.04446177, -0.04435548]),
 'train_r2': array([0.99407516, 0.99415345, 0.99409022, 0.9941086 , 0.99414182])}

In [ ]:
! pip install lightgbm --no-deps  --upgrade --force-reinstall --install-option=--gpu

In [ ]:
import lightgbm as lgb

model_lgb = lgb.LGBMRegressor(device_type="gpu",objective='regression',num_leaves=5,
                              learning_rate=0.05, n_estimators=18000,
                              max_bin = 55, bagging_fraction = 0.8,
                              bagging_freq = 5, feature_fraction = 0.2319,
                              feature_fraction_seed=9, bagging_seed=9,
                              min_data_in_leaf =6, min_sum_hessian_in_leaf = 11)

In [ ]:
 import re

# dfs = [train_data, train_ic50, test_data, test_ic50]
train_data = train_data.rename(columns = lambda x:re.sub('[^A-Za-z0-9_]+', '', x))
test_data = test_data.rename(columns = lambda x:re.sub('[^A-Za-z0-9_]+', '', x))

#model_lgb.fit(train_data, train_ic50)

In [ ]:

yl =model_lgb.predict(test_data)
mse(test_ic50, yl)

In [ ]:
get_cv_scores(model_lgb,train_data, train_ic50)

In [ ]:
!pip install catboost

In [ ]:
from catboost import CatBoostRegressor
model_cat = CatBoostRegressor(
    iterations=10000,
    learning_rate=0.05,
    task_type='GPU')

In [ ]:
#train_ic50.astype('float32')
model_cat.fit(train_data, train_ic50.astype(int)) # catboost throws error if y is float, it should be int
#test_data = test_data.rename(columns = lambda x:re.sub('[^A-Za-z0-9_]+', '', x))

In [ ]:
train_ic50 = np.float32(train_ic50)

In [ ]:
ycat = model_cat.predict(test_data)
mse(test_ic50, ycat)

In [ ]:
import sklearn.metrics as metrics
import math
RMSE= math.sqrt(metrics.mean_squared_error(test_ic50, ycat))
r_square = metrics.r2_score(test_ic50, ycat)
print("R2 :",r_square)
print("RMSE :",RMSE)

In [ ]:
get_cv_scores(model_cat,train_data, train_ic50)

In [ ]:
train_ic50 = pd.DataFrame(train_ic50)

In [ ]:
from sklearn.base import BaseEstimator, TransformerMixin, RegressorMixin
from sklearn.base import clone

class StackingAveragedModels(BaseEstimator, RegressorMixin, TransformerMixin):
    def __init__(self, base_models, meta_model, n_folds=5, use_features_in_secondary=False):
        self.base_models = base_models
        self.meta_model = meta_model
        self.n_folds = n_folds
        self.use_features_in_secondary = use_features_in_secondary
        
    def fit(self, X, y):
        """Fit all the models on the given dataset"""
        self.base_models_ = [list() for x in self.base_models]
        self.meta_model_ = clone(self.meta_model)
        kfold = KFold(n_splits=self.n_folds, shuffle=True, random_state=42)
        
        # Train cloned base models and create out-of-fold predictions
        out_of_fold_predictions = np.zeros((X.shape[0], len(self.base_models)))
        for i, model in enumerate(self.base_models):
            for train_index, holdout_index in kfold.split(X, y):
                instance = clone(model)
                self.base_models_[i].append(instance)
                instance.fit(X.iloc[train_index], y.iloc[train_index])
                y_pred = instance.predict(X.iloc[holdout_index])
                out_of_fold_predictions[holdout_index, i] = y_pred
        
        if self.use_features_in_secondary:
            self.meta_model_.fit(np.hstack((X, out_of_fold_predictions)), y)
        else:
            self.meta_model_.fit(out_of_fold_predictions, y)
            
        return self
    
    def predict(self, X):
        meta_features = np.column_stack([
            np.column_stack([model.predict(X) for model in base_models]).mean(axis=1)
            for base_models in self.base_models_ ])
        if self.use_features_in_secondary:
            return self.meta_model_.predict(np.hstack((X, meta_features)))
        else:
            return self.meta_model_.predict(meta_features)

In [ ]:
stacking_model1 = StackingAveragedModels([model, model_lgb, model_cat], lasso)
stacking_model1.fit(train_data, train_ic50.astype(int))
y_pred = stacking_model1.predict(test_data)

In [ ]:
import math

from sklearn import metrics
RMSE= math.sqrt(metrics.mean_squared_error(test_ic50, y_pred))
r_square = metrics.r2_score(test_ic50, y_pred)
print("R2 :",r_square)
print("RMSE :",RMSE)

In [ ]:
y_pred = pd.DataFrame(y_pred)
from google.colab import files
y_pred.to_csv('pred.csv') 
files.download('pred.csv')

In [ ]:
get_cv_scores(stacking_model1,train_data, train_ic50)

In [ ]:
df = pd.DataFrame(y_pred, columns = ['Predicted IC50'])

In [ ]:
from google.colab import files
test_ic50.to_csv('test.csv') 
files.download('test.csv')

In [ ]:
from google.colab import files
df.to_csv('predicted.csv') 
files.download('predicted.csv')

In [ ]:
from sklearn.model_selection import KFold, cross_val_score
from sklearn.model_selection import cross_validate

n_folds = 5 # number of folds
def get_cv_scores(model, X, y, print_scores=True):
    kf = KFold(n_folds, shuffle=True, random_state=42).get_n_splits(X) # create folds
    scores = cross_validate(model, X, y, cv=kf,
                         scoring=('r2', 'neg_mean_squared_error'),
                         return_train_score=True)
      
    #rmse = -cross_val_score(model, X, y, scoring="neg_mean_squared_error", cv = kf) # get rmse
    #r2 = cross_val_score(model, X, y, scoring="r2", cv = kf) # get rmse
    if print_scores:
      print(scores['test_neg_mean_squared_error'], "Mean MSE :",scores['test_neg_mean_squared_error'].mean())
      print(scores['test_r2'], "Mean R2 :",scores['test_r2'].mean())
    #     print(f'Root mean squared error: {rmse.mean():.3f} ({rmse.std():.3f})')
    #     print(f'R2: {r2.mean():.3f} ({r2.std():.3f})')
    return scores

In [ ]:
get_cv_scores(stacking_model1, train_data, train_ic50)

In [ ]:
from sklearn.base import BaseEstimator, TransformerMixin, RegressorMixin, clone
class AveragingModels(BaseEstimator, RegressorMixin, TransformerMixin):
    def __init__(self, models):
        self.models = models
  #      self.models_ = []
    # we define clones of the original models to fit the data in
    def fit(self, X, y):
        self.models_ = [clone(x) for x in self.models]
        # Train cloned base models
        for model in self.models_:
            model.fit(X, y)
        return self
    #Now we do the predictions for cloned models and average them
    def predict(self, X):
        predictions = np.column_stack([
            model.predict(X) for model in self.models_
        ])
        return np.mean(predictions, axis=1)

In [ ]:
averaged_models = AveragingModels(models = (model, model_lgb, model_cat))
get_cv_scores(averaged_models, train_data, train_ic50)

In [ ]:
drug_encoded

In [ ]:
response_new

# MultiOmics

In [ ]:
import zipfile
!unzip /content/Multiomics_Integrated_data_rna.zip

full_data = pd.read_csv('/content/Multiomics_Integrated_data_rna.zip')

In [ ]:

full_data = pd.read_csv('/content/Multiomics_Integrated_data_rna.zip')

In [ ]:
y = full_data['LN_IC50']
full_data.drop(columns =['LN_IC50'], inplace = True)

In [ ]:
train_data, test_data, train_ic50, test_ic50 = train_test_split( full_data, y, test_size=1/5, random_state=0)

In [ ]:
train_data.drop(columns=['COSMIC_ID', 'DRUG_ID', 'CELL_LINE_NAME', 'PubChem'], inplace= True)
test_data.drop(columns=['COSMIC_ID', 'DRUG_ID', 'CELL_LINE_NAME', 'PubChem'], inplace= True)

In [ ]:
import xgboost
from xgboost import plot_importance
from collections import OrderedDict
lasso = Lasso(alpha =0.0005)
model = xgboost.XGBRegressor(tree_method='gpu_hist',colsample_bytree=0.4,
                 gamma=0,                 
                 learning_rate=0.07,
                 max_depth=9,
                 min_child_weight=1.5,
                 n_estimators=2000,                                                                    
                 reg_alpha=0.75,
                 reg_lambda=0.45,
                 subsample=0.6,
                 seed=42
                 )

In [ ]:
!pip install xgboost

In [ ]:
#m1 = xgboost.XGBRegressor(tree_method='gpu_hist')

In [ ]:
model.fit(train_data, train_ic50)

In [ ]:
def mse(y, y_pred):
    return mean_squared_error(y, y_pred)

In [ ]:
y =model.predict(test_data)
mse(test_ic50, y)

In [ ]:
from sklearn.model_selection import KFold, cross_val_score
from sklearn.model_selection import cross_validate

n_folds = 5 # number of folds
def get_cv_scores(model, X, y, print_scores=True):
    kf = KFold(n_folds, shuffle=True, random_state=42).get_n_splits(X) # create folds
    scores = cross_validate(model, X, y, cv=kf,
                         scoring=('r2', 'neg_mean_squared_error'),
                         return_train_score=True)
      
    #rmse = -cross_val_score(model, X, y, scoring="neg_mean_squared_error", cv = kf) # get rmse
    #r2 = cross_val_score(model, X, y, scoring="r2", cv = kf) # get rmse
    if print_scores:
      print(scores['test_neg_mean_squared_error'], "Mean MSE :",scores['test_neg_mean_squared_error'].mean())
      print(scores['test_r2'], "Mean R2 :",scores['test_r2'].mean())
    #     print(f'Root mean squared error: {rmse.mean():.3f} ({rmse.std():.3f})')
    #     print(f'R2: {r2.mean():.3f} ({r2.std():.3f})')
    return scores

In [ ]:
get_cv_scores(model,train_data, train_ic50)

In [ ]:
def mse(y, y_pred):
    return mean_squared_error(y, y_pred)

In [ ]:
mse(test_ic50, y)

In [ ]:
! pip install lightgbm --no-deps  --upgrade --force-reinstall --install-option=--gpu

In [ ]:
import lightgbm as lgb

model_lgb = lgb.LGBMRegressor(device_type="gpu",objective='regression',num_leaves=5,
                              learning_rate=0.05, n_estimators=18000,
                              max_bin = 55, bagging_fraction = 0.8,
                              bagging_freq = 5, feature_fraction = 0.2319,
                              feature_fraction_seed=9, bagging_seed=9,
                              min_data_in_leaf =6, min_sum_hessian_in_leaf = 11)

In [ ]:
 import re

# dfs = [train_data, train_ic50, test_data, test_ic50]
train_data = train_data.rename(columns = lambda x:re.sub('[^A-Za-z0-9_]+', '', x))
test_data = test_data.rename(columns = lambda x:re.sub('[^A-Za-z0-9_]+', '', x))

In [ ]:
model_lgb.fit(train_data, train_ic50)
yl =model_lgb.predict(test_data)
mse(test_ic50, yl)

In [ ]:
get_cv_scores(model_lgb,train_data, train_ic50)

In [ ]:
!pip install catboost

In [ ]:
from catboost import CatBoostRegressor
model_cat = CatBoostRegressor(
    iterations=10000,
    learning_rate=0.05,
    task_type='GPU')

In [ ]:
model_cat.fit(train_data, train_ic50)
#test_data = test_data.rename(columns = lambda x:re.sub('[^A-Za-z0-9_]+', '', x))

In [ ]:
ycat = model_cat.predict(test_data)
mse(test_ic50, ycat)

In [ ]:
import sklearn.metrics as metrics
import math
RMSE= math.sqrt(metrics.mean_squared_error(test_ic50, ycat))
r_square = metrics.r2_score(test_ic50, ycat)
print("R2 :",r_square)
print("RMSE :",RMSE)

In [ ]:
get_cv_scores(model_cat,train_data, train_ic50)

In [ ]:
class StackingAveragedModels(BaseEstimator, RegressorMixin, TransformerMixin):
    def __init__(self, base_models, meta_model, n_folds=5, use_features_in_secondary=False):
        self.base_models = base_models
        self.meta_model = meta_model
        self.n_folds = n_folds
        self.use_features_in_secondary = use_features_in_secondary
        
    def fit(self, X, y):
        """Fit all the models on the given dataset"""
        self.base_models_ = [list() for x in self.base_models]
        self.meta_model_ = clone(self.meta_model)
        kfold = KFold(n_splits=self.n_folds, shuffle=True, random_state=42)
        
        # Train cloned base models and create out-of-fold predictions
        out_of_fold_predictions = np.zeros((X.shape[0], len(self.base_models)))
        for i, model in enumerate(self.base_models):
            for train_index, holdout_index in kfold.split(X, y):
                instance = clone(model)
                self.base_models_[i].append(instance)
                instance.fit(X.iloc[train_index], y.iloc[train_index])
                y_pred = instance.predict(X.iloc[holdout_index])
                out_of_fold_predictions[holdout_index, i] = y_pred
        
        if self.use_features_in_secondary:
            self.meta_model_.fit(np.hstack((X, out_of_fold_predictions)), y)
        else:
            self.meta_model_.fit(out_of_fold_predictions, y)
            
        return self
    
    def predict(self, X):
        meta_features = np.column_stack([
            np.column_stack([model.predict(X) for model in base_models]).mean(axis=1)
            for base_models in self.base_models_ ])
        if self.use_features_in_secondary:
            return self.meta_model_.predict(np.hstack((X, meta_features)))
        else:
            return self.meta_model_.predict(meta_features)

In [ ]:
stacking_model1 = StackingAveragedModels([model, model_lgb, model_cat], lasso)

In [ ]:
stacking_model1.fit(train_data, train_ic50)

In [ ]:
y_pred = stacking_model1.predict(test_data)

RMSE= math.sqrt(metrics.mean_squared_error(test_ic50, y_pred))
r_square = metrics.r2_score(test_ic50, y_pred)
print("R2 :",r_square)
print("RMSE :",RMSE)

In [ ]:
from sklearn.model_selection import KFold, cross_val_score
from sklearn.model_selection import cross_validate

n_folds = 5 # number of folds
def get_cv_scores(model, X, y, print_scores=True):
    kf = KFold(n_folds, shuffle=True, random_state=42).get_n_splits(X) # create folds
    scores = cross_validate(model, X, y, cv=kf,
                         scoring=('r2', 'neg_mean_squared_error'),
                         return_train_score=True)
      
    #rmse = -cross_val_score(model, X, y, scoring="neg_mean_squared_error", cv = kf) # get rmse
    #r2 = cross_val_score(model, X, y, scoring="r2", cv = kf) # get rmse
    if print_scores:
      print(scores['test_neg_mean_squared_error'], "Mean MSE :",scores['test_neg_mean_squared_error'].mean())
      print(scores['test_r2'], "Mean R2 :",scores['test_r2'].mean())
    #     print(f'Root mean squared error: {rmse.mean():.3f} ({rmse.std():.3f})')
    #     print(f'R2: {r2.mean():.3f} ({r2.std():.3f})')
    return scores

In [ ]:
get_cv_scores(stacking_model1, train_data, train_ic50)

In [ ]:
from sklearn.base import BaseEstimator, TransformerMixin, RegressorMixin, clone
class AveragingModels(BaseEstimator, RegressorMixin, TransformerMixin):
    def __init__(self, models):
        self.models = models
  #      self.models_ = []
    # we define clones of the original models to fit the data in
    def fit(self, X, y):
        self.models_ = [clone(x) for x in self.models]
        # Train cloned base models
        for model in self.models_:
            model.fit(X, y)
        return self
    #Now we do the predictions for cloned models and average them
    def predict(self, X):
        predictions = np.column_stack([
            model.predict(X) for model in self.models_
        ])
        return np.mean(predictions, axis=1)

In [ ]:
averaged_models = AveragingModels(models = (model, model_lgb, model_cat))
get_cv_scores(averaged_models, train_data, train_ic50)